### ISSUE TITLE
Problem installing: Cython, MS Build Tools

### ISSUE THREAD

**Issue by lindsaymarkward** [KeyWeeUsr/KivyInstaller#4]
Hi. I'm trying this tool for installing Kivy with Python on Windows, but it won't work "out of the box".

When I first ran it, it successfully installed up to the point that it said Cython was not installed.  
I can't install Cython before running this, so I don't understand why that's not part of this batch file installation.
After I installed Cython with pip using my newly-installed Python, I had to delete the config file in order to re-run kivy.bat  (When I just ran kivy.bat it said, "The system cannot find the batch label specified - installed".  

Then it complained that the MS Visual Studio Build Tools were required, and aborted the installation again.  
I installed those from the link provided... had to restart the PC... delete the config file and re-run again...

Then I get the following error and I'm not sure what to do next:
```
    creating build\temp.win-amd64-3.5\Release\Users\Wards\AppData\Local\Temp\pip-build-ov3kl892\kivy\kivy\graphics
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IF:\Users\Wards\Documents\dev\KivyInstaller\include -IF:\Users\Wards\Documents\dev\KivyInstaller\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /TcC:\Users\Wards\AppData\Local\Temp\pip-build-ov3kl892\kivy\kivy\graphics\context.c /Fobuild\temp.win-amd64-3.5\Release\Users\Wards\AppData\Local\Temp\pip-build-ov3kl892\kivy\kivy\graphics\context.obj
    context.c
    c:\users\wards\appdata\local\temp\pip-build-ov3kl892\kivy\kivy\graphics\gl_redirect.h(8): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory
     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

I didn't read anything about these extra requirements in the docs.  
I was hoping this tool would install all dependencies.

Thanks :)

**Comment by KeyWeeUsr** [comment]
The only situation I know about that would lead to such requirements is when a user tries to install **stable**(1.9.1) version of Kivy for Python > 3.4, because there are no stable wheel for higher versions. It's Kivy's fault, but it's even mentioned in the installation documentation that Python 3.5 and higher are experimental and latest/master-only wheels (for now).

When the new version of Kivy is released, I think we'll have even 3.5 and 3.6 wheels for the stable.

Also, after Python is installed, the interpreter is already there and working. You should be able to just open the kivy.bat file and use it like a casual cmd with paths set e.g.:

    pip install Cython

and related to MSVC - for now the batch only opens a link in the browser, though I intend to make it install and set paths through batch too in the future.

The best thing would be installing kivy-master version as asked in the batch, because I think the stable version doesn't even work on 3.5 and higher or with MSVC at all just out-of-box and needs some changes or something set in the compiler.

**Comment by KeyWeeUsr** [comment]
Yep, 3.5 as I thought :)

**Comment by lindsaymarkward** [comment]
Thanks very much for the response. I would like a "just works" installation. Otherwise, it seems I could do it manually.   
Do you think you could add defaults so that the installation will work? E.g. when running some Unix commands like `apt-get` you can press enter to select the default option: `Y/n`. 

I think you're saying I can't have Kivy stable + Python 3.5, but I could have Kivy master + Python 3.5...  
If that's the case, then providing defaults that work could be a way to help avoid incompatibilities.

Or, should it be Kivy stable + Python 3.4? If so, then please consider making this the default.

**Comment by KeyWeeUsr** [comment]
I like the idea of the defaults, I'll think about it :)

Re stable + >3.5, that's not a fault of this installer as I said. The change here would only mean another "scheduled" revert when we (kivy) release a new stable version. Sadly, although the new stable has had 2+ dates for the new version, it still hasn't been released.

Although making 3.4 the default version seems a reasonable option, Kivy 1.9.1 is old and drags a bag of issues with it therefore if possible, it'd be better to avoid it as the current master is more stable than the stable itself, thus switching to the new python versions which for now are supported only at master seems a good idea to me for protecting the users from old issues.

On the other hand, the only thing that is the problem with the correct stable installation for py3 is [this line](https://github.com/KeyWeeUsr/KivyInstaller/blob/master/kivy.bat#L16). Change it to `3.4.4` and it'll install old python with kivy 1.9.1 correctly. 👍

**Comment by lindsaymarkward** [comment]
Thank you. I tested this today and it worked. I uninstalled Python first but not the MS tools, so I'm not totally sure.

On your README page, you have the commands:

    mkdir python
    bitsadmin /transfer "GetBatch" "https://git.io/vDDjn" "%cd%\kivy.bat"
    cd python

Should the second and third lines be the other way around, so kivy.bat is downloaded to the python directory?

**Comment by KeyWeeUsr** [comment]
Yeah, thanks for that! I'm blind. It's fixed now :)
